before_install: gem update bundler
cache: bundler
sudo: false
env:
  global:
    - JRUBY_OPTS="$JRUBY_OPTS --debug" # for simplecov
language: ruby
script: "bundle exec rake ci"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
  - jruby-18mode
  - jruby-19mode
  - jruby-head
  - rbx-2
  - ree
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
  fast_finish: true
notifications:
  irc:
    channels:
      - irc.freenode.org#rom-rb
    on_success: never
    on_failure: change
